import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'हिंदी (Hindi)', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ் (Tamil)', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు (Telugu)', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी (Marathi)', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা (Bengali)', flag: '🇮🇳' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)', flag: '🇮🇳' },
  { code: 'es', name: 'Español (Spanish)', flag: '🇪🇸' }
];

export const TRANSLATIONS = {
  en: {
    brandName: 'ServiceHub',
    tagline: 'Multi-Vendor Service Marketplace',
    home: 'Home',
    exploreServices: 'Explore Services',
    categories: 'Categories',
    cart: 'Cart',
    login: 'Sign In',
    registerCustomer: 'Customer Sign Up',
    registerPartner: 'Partner Business Registration',
    myBookings: 'My Bookings',
    myDashboard: 'Dashboard',
    adminConsole: 'Admin Console',
    logout: 'Sign Out',
    demoAccounts: 'Demo Accounts',
    searchPlaceholder: 'Search haircut, home deep cleaning, car wash...',
    allCategories: 'All Categories',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    filterByArea: 'Filter by area...',
    sortBy: 'Sort By',
    recommended: 'Recommended',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    ratingHighLow: 'Rating: High to Low',
    bookNow: 'Book Appointment',
    viewStorefront: 'View Storefront',
    kycVerified: 'KYC Verified Business',
    footerRights: 'ServiceHub Marketplace. All rights reserved.',
    heroTitle: 'Book Verified On-Demand Services Near You',
    heroSubtitle: 'Instant home deep cleaning, beauty salon, car wash & personal training booked with non-conflicting time slots.',
    popularCategories: 'Popular Service Categories',
    topRatedServices: 'Top Rated Services Near You',
    whyChooseTitle: 'Why Choose ServiceHub Marketplace',
    instantSlotPicker: 'Instant Slot Picker',
    transparentPricing: 'Transparent Pricing',
    singleProviderGuard: 'Single Provider Cart Guard',
    partnerCtaTitle: 'Grow your service business with ServiceHub',
    partnerCtaDesc: 'Join verified service merchants offering services to thousands of customers.',
    becomePartnerBtn: 'Register as Business Partner',
    myAddressesTab: 'My Addresses',
    updateProfileTab: 'Update Personal Details',
    activeBookingsMetric: 'Active Bookings',
    completedServicesMetric: 'Completed Services',
    totalSpentMetric: 'Total Spent',
    rateAndReview: 'Rate & Review',
    cancelBooking: 'Cancel Booking',
    addAddressBtn: 'Add New Address',
    saveAddressBtn: 'Save Address',
    saveProfileBtn: 'Save Personal Details',
    pendingPartnerKyc: 'Pending Partner KYC',
    pendingCustomers: 'Pending Customers',
    allPartners: 'All Partners',
    usersRegistry: 'Users Registry',
    approveBtn: 'Approve',
    rejectBtn: 'Reject',
    suspendBtn: 'Suspend'
  },
  hi: {
    brandName: 'सर्विसहब',
    tagline: 'मल्टी-वेंडर सेवा बाज़ार',
    home: 'मुख्य पृष्ठ',
    exploreServices: 'सेवाएं खोजें',
    categories: 'श्रेणियां',
    cart: 'कार्ट',
    login: 'साइन इन',
    registerCustomer: 'ग्राहक पंजीकरण',
    registerPartner: 'बिजनेस पार्टनर पंजीकरण',
    myBookings: 'मेरी बुकिंग',
    myDashboard: 'डैशबोर्ड',
    adminConsole: 'एडमिन कंसोल',
    logout: 'साइन आउट',
    demoAccounts: 'डेमो खाते',
    searchPlaceholder: 'हेयरकट, सफाई, कार वॉश खोजें...',
    allCategories: 'सभी श्रेणियां',
    minPrice: 'न्यूनतम मूल्य',
    maxPrice: 'अधिकतम मूल्य',
    filterByArea: 'क्षेत्र द्वारा फ़िल्टर करें...',
    sortBy: 'क्रमानुक्रम',
    recommended: 'अनुशंसित',
    priceLowHigh: 'मूल्य: कम से अधिक',
    priceHighLow: 'मूल्य: अधिक से कम',
    ratingHighLow: 'रेटिंग: उच्चतम',
    bookNow: 'अपॉइंटमेंट बुक करें',
    viewStorefront: 'स्टोरफ़्रंट देखें',
    kycVerified: 'केवाईसी सत्यापित व्यवसाय',
    footerRights: 'सर्विसहब मार्केटप्लेस। सर्वाधिकार सुरक्षित।',
    heroTitle: 'अपने निकट सत्यापित ऑन-डिमांड सेवाएं बुक करें',
    heroSubtitle: 'सफाई, ब्यूटी सैलून, कार वॉश और पर्सनल ट्रेनिंग के लिए गैर-विरोधी समय स्लॉट के साथ तुरंत बुकिंग करें।',
    popularCategories: 'लोकप्रिय सेवा श्रेणियां',
    topRatedServices: 'आपके निकट शीर्ष रेटेड सेवाएं',
    whyChooseTitle: 'सर्विसहब मार्केटप्लेस क्यों चुनें',
    instantSlotPicker: 'त्वरित स्लॉट चयन',
    transparentPricing: 'पारदर्शी मूल्य निर्धारण',
    singleProviderGuard: 'सिंगल प्रदाता कार्ट सुरक्षा',
    partnerCtaTitle: 'सर्विसहब के साथ अपना सेवा व्यवसाय बढ़ाएं',
    partnerCtaDesc: 'हजारों ग्राहकों को सेवाएं देने वाले सत्यापित व्यवसाय मर्चेंट में शामिल हों।',
    becomePartnerBtn: 'बिजनेस पार्टनर के रूप में पंजीकरण करें',
    myAddressesTab: 'मेरे पते',
    updateProfileTab: 'व्यक्तिगत विवरण अपडेट करें',
    activeBookingsMetric: 'सक्रिय बुकिंग',
    completedServicesMetric: 'पूर्ण सेवाएं',
    totalSpentMetric: 'कुल खर्च',
    rateAndReview: 'रेट और समीक्षा करें',
    cancelBooking: 'बुकिंग रद्द करें',
    addAddressBtn: 'नया पता जोड़ें',
    saveAddressBtn: 'पता सहेजें',
    saveProfileBtn: 'व्यक्तिगत विवरण सहेजें',
    pendingPartnerKyc: 'लंबित पार्टनर केवाईसी',
    pendingCustomers: 'लंबित ग्राहक',
    allPartners: 'सभी पार्टनर',
    usersRegistry: 'उपयोगकर्ता रजिस्ट्रार',
    approveBtn: 'स्वीकृत करें',
    rejectBtn: 'अस्वीकार करें',
    suspendBtn: 'निलंबित करें'
  },
  ta: {
    brandName: 'சர்வீஸ்ஹப்',
    tagline: 'மல்டி-வெண்டர் சேவை சந்தை',
    home: 'முகப்பு',
    exploreServices: 'சேவைகளை ஆராய்க',
    categories: 'வகைகள்',
    cart: 'கார்ட்',
    login: 'உள்நுழைக',
    registerCustomer: 'வாடிக்கையாளர் பதிவு',
    registerPartner: 'வணிக பங்குதாரர் பதிவு',
    myBookings: 'எனது முன்பதிவுகள்',
    myDashboard: 'டாஷ்போர்டு',
    adminConsole: 'நிர்வாக கன்சோல்',
    logout: 'வெளியேறு',
    demoAccounts: 'டெமோ கணக்குகள்',
    searchPlaceholder: 'ஹேர்கட், துப்புரவு, கார் வாஷ் தேடுக...',
    allCategories: 'அனைத்து பிரிவுகள்',
    minPrice: 'குறைந்தபட்ச விலை',
    maxPrice: 'அதிகபட்ச விலை',
    filterByArea: 'பகுதி வாரியாக வடிகட்டவும்...',
    sortBy: 'வரிசைப்படுத்து',
    recommended: 'பரிந்துரைக்கப்பட்டவை',
    priceLowHigh: 'விலை: குறைந்ததிலிருந்து அதிகம்',
    priceHighLow: 'விலை: அதிகத்திலிருந்து குறைவு',
    ratingHighLow: 'மதிப்பீடு: அதிகம்',
    bookNow: 'முன்பதிவு செய்',
    viewStorefront: 'கடையை பார்',
    kycVerified: 'கேஒய்சி சரிபார்க்கப்பட்டது',
    footerRights: 'சர்வீஸ்ஹப் சந்தை. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    heroTitle: 'உங்களுக்கு அருகில் சரிபார்க்கப்பட்ட சேவைகளை முன்பதிவு செய்யுங்கள்',
    heroSubtitle: 'துப்புரவு, அழகு நிலையம் மற்றும் கார் வாஷ் சேவைகளுக்கான விரைவான முன்பதிவு.',
    popularCategories: 'பிரபலமான சேவை பிரிவுகள்',
    topRatedServices: 'உயர்ந்த மதிப்பீடு பெற்ற சேவைகள்',
    whyChooseTitle: 'ஏன் சர்வீஸ்ஹப் தேர்வு செய்ய வேண்டும்',
    instantSlotPicker: 'உடனடி நேர தேர்வு',
    transparentPricing: 'வெளிப்படையான விலை நிர்ணயம்',
    singleProviderGuard: 'ஒற்றை வழங்குநர் பாதுகாப்பு',
    partnerCtaTitle: 'சர்வீஸ்ஹப் மூலம் உங்கள் வணிகத்தை வளர்க்கவும்',
    partnerCtaDesc: 'ஆயிரக்கணக்கான வாடிக்கையாளர்களுக்கு சேவை செய்யும் வணிகர்களில் இணையுங்கள்.',
    becomePartnerBtn: 'பங்குதாரராக பதிவு செய்க',
    myAddressesTab: 'எனது முகவரிகள்',
    updateProfileTab: 'சுயவிவரத்தை புதுப்பிக்கவும்',
    activeBookingsMetric: 'செயலில் உள்ள முன்பதிவுகள்',
    completedServicesMetric: 'நிறைவடைந்த சேவைகள்',
    totalSpentMetric: 'மொத்த செலவு',
    rateAndReview: 'மதிப்பிடவும்',
    cancelBooking: 'ரத்து செய்',
    addAddressBtn: 'புதிய முகவரி சேர்',
    saveAddressBtn: 'முகவரியைச் சேமி',
    saveProfileBtn: 'விவரங்களைச் சேமி',
    pendingPartnerKyc: 'நிலுவையில் உள்ள கேஒய்சி',
    pendingCustomers: 'நிலுவையில் உள்ள வாடிக்கையாளர்கள்',
    allPartners: 'அனைத்து பங்குதாரர்கள்',
    usersRegistry: 'பயனர்கள் பதிவு',
    approveBtn: 'ஒப்புதல் அளி',
    rejectBtn: 'நிராகரி',
    suspendBtn: 'நிறுத்தி வை'
  },
  te: {
    brandName: 'సర్వీస్హబ్',
    tagline: 'మల్టీ-వెండర్ సేవల మార్కెట్‌ప్లేస్',
    home: 'హోమ్',
    exploreServices: 'సేవలను అన్వేషించండి',
    categories: 'కేటగిరీలు',
    cart: 'కార్ట్',
    login: 'సైన్ ఇన్',
    registerCustomer: 'కస్టమర్ రిజిస్ట్రేషన్',
    registerPartner: 'బిజినెస్ పార్టనర్ రిజిస్ట్రేషన్',
    myBookings: 'నా బుకింగ్‌లు',
    myDashboard: 'డాష్‌బోర్డ్',
    adminConsole: 'అడ్మిన్ కన్సోల్',
    logout: 'సైన్ అవుట్',
    demoAccounts: 'డెమో ఖాతాలు',
    searchPlaceholder: 'హెయిర్‌కట్, హోమ్ క్లీనింగ్, కార్ వాష్ శోధించండి...',
    allCategories: 'అన్ని కేటగిరీలు',
    minPrice: 'కనీస ధర',
    maxPrice: 'గరిష్ట ధర',
    filterByArea: 'ప్రాంతం ద్వారా ఫిల్టర్ చేయండి...',
    sortBy: 'సార్ట్ చేయండి',
    recommended: 'సిఫార్సు చేయబడినవి',
    priceLowHigh: 'ధర: తక్కువ నుండి ఎక్కువ',
    priceHighLow: 'ధర: ఎక్కువ నుండి తక్కువ',
    ratingHighLow: 'రేటింగ్: ఎక్కువ',
    bookNow: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    viewStorefront: 'స్టోర్ఫ్రంట్ చూడండి',
    kycVerified: 'కెవైసి సరిచూడబడింది',
    footerRights: 'సర్వీస్హబ్ మార్కెట్‌ప్లేస్. సర్వహక్కులు రక్షించబడ్డాయి.',
    heroTitle: 'మీ దగ్గర ధృవీకరించబడిన సేవలను బుక్ చేసుకోండి',
    heroSubtitle: 'హోమ్ క్లీనింగ్, బ్యూటీ సెలూన్ మరియు కార్ వాష్ కోసం తక్షణ బుకింగ్.',
    popularCategories: 'పాపులర్ కేటగిరీలు',
    topRatedServices: 'టాప్ రేటెడ్ సేవలు',
    whyChooseTitle: 'సర్వీస్హబ్ ఎందుకు ఎంచుకోవాలి',
    instantSlotPicker: 'తక్షణ స్లాట్ ఎంపిక',
    transparentPricing: 'పారదర్శక ధరలు',
    singleProviderGuard: 'సింగిల్ ప్రొవైడర్ కార్ట్ భద్రత',
    partnerCtaTitle: 'సర్వీస్హబ్‌తో మీ వ్యాపారాన్ని పెంచుకోండి',
    partnerCtaDesc: 'వేలాది కస్టమర్లకు సేవలను అందించే వ్యాపారులలో చేరండి.',
    becomePartnerBtn: 'బిజినెస్ పార్టనర్‌గా నమోదు చేసుకోండి',
    myAddressesTab: 'నా చిరునామాలు',
    updateProfileTab: 'వివరాలను నవీకరించండి',
    activeBookingsMetric: 'యాక్టివ్ బుకింగ్‌లు',
    completedServicesMetric: 'పూర్తయిన సేవలు',
    totalSpentMetric: 'మొత్తం ఖర్చు',
    rateAndReview: 'రేటింగ్ ఇవ్వండి',
    cancelBooking: 'రద్దు చేయండి',
    addAddressBtn: 'కొత్త చిరునామా జోడించండి',
    saveAddressBtn: 'చిరునామా సేవ్ చేయండి',
    saveProfileBtn: 'వివరాలు సేవ్ చేయండి',
    pendingPartnerKyc: 'పెండింగ్ కెవైసి',
    pendingCustomers: 'పెండింగ్ కస్టమర్లు',
    allPartners: 'అన్ని పార్టనర్లు',
    usersRegistry: 'యూజర్ల జాబితా',
    approveBtn: 'ఆమోదించండి',
    rejectBtn: 'తిరస్కరించండి',
    suspendBtn: 'సస్పెండ్ చేయండి'
  },
  kn: {
    brandName: 'ಸರ್ವಿಸ್‌ಹಬ್',
    tagline: 'ಮಲ್ಟಿ-ವೆಂಡರ್ ಸೇವಾ ಮಾರುಕಟ್ಟೆ',
    home: 'ಮುಖಪುಟ',
    exploreServices: 'ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ',
    categories: 'ವರ್ಗಗಳು',
    cart: 'ಕಾರ್ಟ್',
    login: 'ಸೈನ್ ಇನ್',
    registerCustomer: 'ಗ್ರಾಹಕರ ನೋಂದಣಿ',
    registerPartner: 'ಪಾಲುದಾರ ಉದ್ಯಮ ನೋಂದಣಿ',
    myBookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    myDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    adminConsole: 'ಅಡ್ಮಿನ್ ಕನ್ಸೋಲ್',
    logout: 'ಸೈನ್ ಔಟ್',
    demoAccounts: 'ಡೆಮೊ ಖಾತೆಗಳು',
    searchPlaceholder: 'ಹೇರ್‌ಕಟ್, ಕ್ಲೀನಿಂಗ್, ಕಾರ್ ವಾಶ್ ಹುಡುಕಿ...',
    allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    minPrice: 'ಕನಿಷ್ಠ ಬೆಲೆ',
    maxPrice: 'ಗರಿಷ್ಠ ಬೆಲೆ',
    filterByArea: 'ಪ್ರದೇಶದ ಪ್ರಕಾರ ಫಿಲ್ಟರ್ ಮಾಡಿ...',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    recommended: 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    priceLowHigh: 'ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿಗೆ',
    priceHighLow: 'ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆಗೆ',
    ratingHighLow: 'ರೇಟಿಂಗ್: ಗರಿಷ್ಠ',
    bookNow: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    viewStorefront: 'ಸ್ಟೋರ್ ಪ್ರದರ್ಶನ ನೋಡಿ',
    kycVerified: 'ಕೆವೈಸಿ ಪರಿಶೀಲಿತ ಉದ್ಯಮ',
    footerRights: 'ಸರ್ವಿಸ್‌ಹಬ್ ಮಾರುಕಟ್ಟೆ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    heroTitle: 'ನಿಮ್ಮ ಬಳಿ ಪರಿಶೀಲಿಸಿದ ಸೇವೆಗಳನ್ನು ಕಾಯ್ದಿರಿಸಿ',
    heroSubtitle: 'ಮನೆ ಸ್ವಚ್ಛತೆ, ಬ್ಯೂಟಿ ಸಲೂನ್ ಮತ್ತು ಕಾರ್ ವಾಶ್‌ಗಾಗಿ ತ್ವರಿತ ಬುಕಿಂಗ್.',
    popularCategories: 'ಜನಪ್ರಿಯ ಸೇವಾ ವರ್ಗಗಳು',
    topRatedServices: 'ಉನ್ನತ ಶ್ರೇಣಿಯ ಸೇವೆಗಳು',
    whyChooseTitle: 'ಸರ್ವಿಸ್‌ಹಬ್ ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು',
    instantSlotPicker: 'ತ್ವರಿತ ಸಮಯ ಆಯ್ಕೆ',
    transparentPricing: 'ಪಾರದರ್ಶಕ ಬೆಲೆ',
    singleProviderGuard: 'ಏಕ ಪೂರೈಕೆದಾರ ರಕ್ಷಣೆ',
    partnerCtaTitle: 'ಸರ್ವಿಸ್‌ಹಬ್‌ನೊಂದಿಗೆ ನಿಮ್ಮ ವ್ಯವಹಾರ ಬೆಳೆಸಿ',
    partnerCtaDesc: 'ಸಾವಿರಾರು ಗ್ರಾಹಕರಿಗೆ ಸೇವೆ ನೀಡುವ ವ್ಯಾಪಾರಿಗಳೊಂದಿಗೆ ಸೇರಿ.',
    becomePartnerBtn: 'ವ್ಯಾಪಾರ ಪಾಲುದಾರರಾಗಿ ನೋಂದಾಯಿಸಿ',
    myAddressesTab: 'ನನ್ನ ವಿಳಾಸಗಳು',
    updateProfileTab: 'ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ',
    activeBookingsMetric: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು',
    completedServicesMetric: 'ಪೂರ್ಣಗೊಂಡ ಸೇವೆಗಳು',
    totalSpentMetric: 'ಒಟ್ಟು ವೆಚ್ಚ',
    rateAndReview: 'ರೇಟಿಂಗ್ ನೀಡಿ',
    cancelBooking: 'ರದ್ದುಗೊಳಿಸಿ',
    addAddressBtn: 'ಹೊಸ ವಿಳಾಸ ಸೇರಿಸಿ',
    saveAddressBtn: 'ವಿಳಾಸ ಉಳಿಸಿ',
    saveProfileBtn: 'ವಿವರಗಳನ್ನು ಉಳಿಸಿ',
    pendingPartnerKyc: 'ಬಾಕಿ ಇರುವ ಕೆವೈಸಿ',
    pendingCustomers: 'ಬಾಕಿ ಇರುವ ಗ್ರಾಹಕರು',
    allPartners: 'ಎಲ್ಲಾ ಪಾಲುದಾರರು',
    usersRegistry: 'ಬಳಕೆದಾರರ ಪಟ್ಟಿ',
    approveBtn: 'ಅನುಮೋದಿಸಿ',
    rejectBtn: 'ನಿರಾಕರಿಸಿ',
    suspendBtn: 'ಅಮಾನತುಗೊಳಿಸಿ'
  },
  mr: {
    brandName: 'सर्व्हिसहब',
    tagline: 'मल्टी-व्हेंडर सेवा मार्केटप्लेस',
    home: 'मुख्यपृष्ठ',
    exploreServices: 'सेवा शोधा',
    categories: 'श्रेणी',
    cart: 'कार्ट',
    login: 'साइन इन',
    registerCustomer: 'ग्राहक नोंदणी',
    registerPartner: 'बिझनेस पार्टनर नोंदणी',
    myBookings: 'माझ्या बुकिंग्स',
    myDashboard: 'डॅशबोर्ड',
    adminConsole: 'ॲडमिन कन्सोल',
    logout: 'साइन आउट',
    demoAccounts: 'डेमो खाती',
    searchPlaceholder: 'हेअरकट, घराची स्वच्छता, कार वॉश शोधा...',
    allCategories: 'सर्व श्रेणी',
    minPrice: 'कमीत कमी किंमत',
    maxPrice: 'जास्तीत जास्त किंमत',
    filterByArea: 'परिसरानुसार फिल्टर करा...',
    sortBy: 'क्रमवारी लावा',
    recommended: 'शीर्ष शिफारस',
    priceLowHigh: 'किंमत: कमी ते जास्त',
    priceHighLow: 'किंमत: जास्त ते कमी',
    ratingHighLow: 'रेटिंग: सर्वोच्च',
    bookNow: 'अपॉइंटमेंट बुक करा',
    viewStorefront: 'स्टोअरफ्रंट पहा',
    kycVerified: 'केवायसी सत्यापित व्यवसाय',
    footerRights: 'सर्व्हिसहब मार्केटप्लेस. सर्व हक्क सुरक्षित.',
    heroTitle: 'तुमच्या जवळ सत्यापित सेवा बुक करा',
    heroSubtitle: 'स्वच्छता, ब्यूटी सलून आणि कार वॉशसाठी झटपट बुकिंग.',
    popularCategories: 'लोकप्रिय सेवा श्रेणी',
    topRatedServices: 'सर्वोच्च रेट केलेल्या सेवा',
    whyChooseTitle: 'सर्व्हिसहब का निवडावे',
    instantSlotPicker: 'झटपट वेळ निवड',
    transparentPricing: 'पारदर्शक दर',
    singleProviderGuard: 'सिंगल प्रदाता सुरक्षा',
    partnerCtaTitle: 'सर्व्हिसहब सोबत आपला व्यवसाय वाढवा',
    partnerCtaDesc: 'हजारो ग्राहकांना सेवा देणाऱ्या व्यापाऱ्यांमध्ये सामील व्हा.',
    becomePartnerBtn: 'पार्टनर म्हणून नोंदणी करा',
    myAddressesTab: 'माझे पत्ते',
    updateProfileTab: 'माहिती अद्ययावत करा',
    activeBookingsMetric: 'सक्रिय बुकिंग्स',
    completedServicesMetric: 'पूर्ण झालेल्या सेवा',
    totalSpentMetric: 'एकूण खर्च',
    rateAndReview: 'रेटिंग द्या',
    cancelBooking: 'बुकिंग रद्द करा',
    addAddressBtn: 'नवीन पत्ता जोडा',
    saveAddressBtn: 'पत्ता जतन करा',
    saveProfileBtn: 'माहिती जतन करा',
    pendingPartnerKyc: 'प्रलंबित केवायसी',
    pendingCustomers: 'प्रलंबित ग्राहक',
    allPartners: 'सर्व पार्टनर',
    usersRegistry: 'वापरकर्ते यादी',
    approveBtn: 'मंजूर करा',
    rejectBtn: 'नाकारा',
    suspendBtn: 'निलंबित करा'
  },
  bn: {
    brandName: 'সার্ভিসহাব',
    tagline: 'মাল্টি-ভেন্ডর সেবা মার্কেটপ্লেস',
    home: 'হোম',
    exploreServices: 'সেবা অন্বেষণ করুন',
    categories: 'ক্যাটাগরি',
    cart: 'কার্ট',
    login: 'সাইন ইন',
    registerCustomer: 'গ্রাহক নিবন্ধন',
    registerPartner: 'বিজনেস পার্টনার নিবন্ধন',
    myBookings: 'আমার বুকিং',
    myDashboard: 'ড্যাশবোর্ড',
    adminConsole: 'অ্যাডমিন কনসোল',
    logout: 'সাইন আউট',
    demoAccounts: 'ডেমো অ্যাকাউন্ট',
    searchPlaceholder: 'হেয়ারকাট, হোম ক্লিনিং, কার ওয়াশ খুঁজুন...',
    allCategories: 'সকল ক্যাটাগরি',
    minPrice: 'সর্বনিম্ন মূল্য',
    maxPrice: 'সর্বোচ্চ মূল্য',
    filterByArea: 'এলাকা অনুযায়ী ফিল্টার করুন...',
    sortBy: 'ক্রমানুসারে সাজান',
    recommended: 'সুপারিশকৃত',
    priceLowHigh: 'মূল্য: কম থেকে বেশি',
    priceHighLow: 'মূল্য: বেশি থেকে কম',
    ratingHighLow: 'রেটিং: সর্বোচ্চ',
    bookNow: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    viewStorefront: 'স্টোরফ্রন্ট দেখুন',
    kycVerified: 'কেওয়াইসি যাচাইকৃত ব্যবসা',
    footerRights: 'সার্ভিসহাব মার্কেটপ্লেস। সর্বস্বত্ব সংরক্ষিত।',
    heroTitle: 'আপনার কাছে যাচাইকৃত সেবা বুক করুন',
    heroSubtitle: 'হোম ক্লিনিং, বিউটি পার্লার এবং কার ওয়াশের দ্রুত বুকিং।',
    popularCategories: 'জনপ্রিয় সেবা ক্যাটাগরি',
    topRatedServices: 'সেরা রেটিং প্রাপ্ত সেবা',
    whyChooseTitle: 'কেন সার্ভিসহাব বেছে নেবেন',
    instantSlotPicker: 'তাত্ক্ষণিক সময় নির্বাচন',
    transparentPricing: 'স্বচ্ছ মূল্য নির্ধারণ',
    singleProviderGuard: 'একক প্রদানকারী সুরক্ষা',
    partnerCtaTitle: 'সার্ভিসহাবের সাথে আপনার ব্যবসা বাড়ান',
    partnerCtaDesc: 'হাজার হাজার গ্রাহকদের সেবা প্রদানকারী ব্যবসায়ীদের সাথে যুক্ত হন।',
    becomePartnerBtn: 'পার্টনার হিসেবে নিবন্ধন করুন',
    myAddressesTab: 'আমার ঠিকানা',
    updateProfileTab: 'তথ্য আপডেট করুন',
    activeBookingsMetric: 'সক্রিয় বুকিং',
    completedServicesMetric: 'সম্পন্ন সেবা',
    totalSpentMetric: 'মোট ব্যয়',
    rateAndReview: 'রেটিং দিন',
    cancelBooking: 'বুকিং বাতিল করুন',
    addAddressBtn: 'নতুন ঠিকানা যোগ করুন',
    saveAddressBtn: 'ঠিকানা সংরক্ষণ করুন',
    saveProfileBtn: 'তথ্য সংরক্ষণ করুন',
    pendingPartnerKyc: 'অপেক্ষমাণ কেওয়াইসি',
    pendingCustomers: 'অপেক্ষমাণ গ্রাহক',
    allPartners: 'সকল পার্টনার',
    usersRegistry: 'ব্যবহারকারী তালিকা',
    approveBtn: 'অনুমোদন দিন',
    rejectBtn: 'প্রত্যাখ্যান করুন',
    suspendBtn: 'স্থগিত করুন'
  },
  gu: {
    brandName: 'સર્વિસહબ',
    tagline: 'મલ્ટી-વેન્ડર સેવા માર્કેટપ્લેસ',
    home: 'હોમ',
    exploreServices: 'સેવાઓ શોધો',
    categories: 'કેટેગરીઝ',
    cart: 'કાર્ટ',
    login: 'સાઇન ઇન',
    registerCustomer: 'ગ્રાહક રજીસ્ટ્રેશન',
    registerPartner: 'બિઝનેસ પાર્ટનર રજીસ્ટ્રેશન',
    myBookings: 'મારી બુકિંગ્સ',
    myDashboard: 'ડેશબોર્ડ',
    adminConsole: 'એડમિન કન્સોલ',
    logout: 'સાઇન આઉટ',
    demoAccounts: 'ડેમો એકાઉન્ટ્સ',
    searchPlaceholder: 'હેરકટ, હોમ ક્લીનિંગ, કાર વોશ શોધો...',
    allCategories: 'બધી કેટેગરીઝ',
    minPrice: 'ન્યૂનતમ કિંમત',
    maxPrice: 'મહત્તમ કિંમત',
    filterByArea: 'વિસ્તાર મુજબ ફિલ્ટર કરો...',
    sortBy: 'ગોઠવો',
    recommended: 'ભલામણ કરેલ',
    priceLowHigh: 'કિંમત: ઓછી થી વધુ',
    priceHighLow: 'કિંમત: વધુ થી ઓછી',
    ratingHighLow: 'રેટિંગ: ઉચ્ચત્તમ',
    bookNow: 'એપોઇન્ટમેન્ટ બુક કરો',
    viewStorefront: 'સ્ટોરફ્રન્ટ જુઓ',
    kycVerified: 'કેવાયસી ચકાસાયેલ વ્યવસાય',
    footerRights: 'સર્વિસહબ માર્કેટપ્લેસ. સર્વાધિકાર સુરક્ષિત.',
    heroTitle: 'તમારી નજીક ચકાસાયેલ સેવાઓ બુક કરો',
    heroSubtitle: 'સફાઈ, બ્યુટી પાર્લર અને કાર વોશ માટે ઝડપી બુકિંગ.',
    popularCategories: 'લોકપ્રિય સેવા કેટેગરીઝ',
    topRatedServices: 'ટોચની રેટ કરેલી સેવાઓ',
    whyChooseTitle: 'શા માટે સર્વિસહબ પસંદ કરવું',
    instantSlotPicker: 'ઝડપી સમય પસંદગી',
    transparentPricing: 'પારદર્શક ભાવ',
    singleProviderGuard: 'સિંગલ પ્રોવાઇડર સુરક્ષા',
    partnerCtaTitle: 'સર્વિસહબ સાથે તમારો વ્યવસાય વધારો',
    partnerCtaDesc: 'હજારો ગ્રાહકોને સેવા આપતા વેપારીઓમાં જોડાઓ.',
    becomePartnerBtn: 'બિઝનેસ પાર્ટનર તરીકે નોંધણી કરો',
    myAddressesTab: 'મારા સરનામા',
    updateProfileTab: 'વિગતો અપડેટ કરો',
    activeBookingsMetric: 'સક્રિય બુકિંગ્સ',
    completedServicesMetric: 'પૂર્ણ થયેલ સેવાઓ',
    totalSpentMetric: 'કુલ ખર્ચ',
    rateAndReview: 'રેટિંગ આપો',
    cancelBooking: 'બુકિંગ કેન્સલ કરો',
    addAddressBtn: 'નવું સરનામું ઉમેરો',
    saveAddressBtn: 'સરનામું સાચવો',
    saveProfileBtn: 'વિગતો સાચવો',
    pendingPartnerKyc: 'પેન્ડિંગ કેવાયસી',
    pendingCustomers: 'પેન્ડિંગ ગ્રાહકો',
    allPartners: 'બધા પાર્ટનર્સ',
    usersRegistry: 'વપરાશકર્તા યાદી',
    approveBtn: 'મંજૂર કરો',
    rejectBtn: 'નામંજૂર કરો',
    suspendBtn: 'સસ્પેન્ડ કરો'
  },
  es: {
    brandName: 'ServiceHub',
    tagline: 'Mercado de Servicios Multivendedor',
    home: 'Inicio',
    exploreServices: 'Explorar Servicios',
    categories: 'Categorías',
    cart: 'Carrito',
    login: 'Iniciar Sesión',
    registerCustomer: 'Registro de Cliente',
    registerPartner: 'Registro de Empresa Socia',
    myBookings: 'Mis Reservas',
    myDashboard: 'Panel',
    adminConsole: 'Consola de Administración',
    logout: 'Cerrar Sesión',
    demoAccounts: 'Cuentas de Demostración',
    searchPlaceholder: 'Buscar corte de pelo, limpieza del hogar, lavado de autos...',
    allCategories: 'Todas las Categorías',
    minPrice: 'Precio Mínimo',
    maxPrice: 'Precio Máximo',
    filterByArea: 'Filtrar por zona...',
    sortBy: 'Ordenar Por',
    recommended: 'Recomendado',
    priceLowHigh: 'Precio: Menor a Mayor',
    priceHighLow: 'Precio: Mayor a Menor',
    ratingHighLow: 'Calificación: Mayor a Menor',
    bookNow: 'Reservar Cita',
    viewStorefront: 'Ver Tienda',
    kycVerified: 'Empresa Verificada por KYC',
    footerRights: 'ServiceHub Marketplace. Todos los derechos reservados.',
    heroTitle: 'Reserve Servicios Verificados Cerca de Usted',
    heroSubtitle: 'Limpieza profunda del hogar, salón de belleza y lavado de autos reservados al instante.',
    popularCategories: 'Categorías de Servicios Populares',
    topRatedServices: 'Servicios Mejor Calificados Cerca de Usted',
    whyChooseTitle: 'Por qué elegir ServiceHub Marketplace',
    instantSlotPicker: 'Selección de Horario Instantánea',
    transparentPricing: 'Precios Transparentes',
    singleProviderGuard: 'Protección de Carrito de Proveedor Único',
    partnerCtaTitle: 'Haga crecer su negocio de servicios con ServiceHub',
    partnerCtaDesc: 'Únase a comerciantes de servicios verificados que atienden a miles de clientes.',
    becomePartnerBtn: 'Registrarse como Socio de Negocio',
    myAddressesTab: 'Mis Direcciones',
    updateProfileTab: 'Actualizar Datos Personales',
    activeBookingsMetric: 'Reservas Activas',
    completedServicesMetric: 'Servicios Completados',
    totalSpentMetric: 'Gasto Total',
    rateAndReview: 'Calificar y Reseñar',
    cancelBooking: 'Cancelar Reserva',
    addAddressBtn: 'Agregar Nueva Dirección',
    saveAddressBtn: 'Guardar Dirección',
    saveProfileBtn: 'Guardar Datos Personales',
    pendingPartnerKyc: 'KYC de Socio Pendiente',
    pendingCustomers: 'Clientes Pendientes',
    allPartners: 'Todos los Socios',
    usersRegistry: 'Registro de Usuarios',
    approveBtn: 'Aprobar',
    rejectBtn: 'Rechazar',
    suspendBtn: 'Suspender'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('servicehub_lang') || 'en';
  });

  const changeLanguage = (code) => {
    setLanguage(code);
    localStorage.setItem('servicehub_lang', code);
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
